repos:
    - repo: local
      hooks:
        - id: isort
          name: isort
          entry: isort --settings-file ./config.isort .
          language: system
          types: [python]
          pass_filenames: false
          
    - repo: local
      hooks:
        - id: black
          name: black
          entry: black --config ./config.black .
          language: system
          types: [python]
          pass_filenames: false
          
    - repo: local
      hooks:
        - id: flake8
          name: flake8
          entry: flake8 --config config.flake8 .
          language: system
          types: [python]
          pass_filenames: false

    - repo: local
      hooks:
        - id: mypy
          name: mypy
          entry: mypy --config config.mypy .
          language: system
          types: [python]
          pass_filenames: false

    


